const assert=require('node:assert/strict');
const math=require('../billing-math.js');
const prices=[{code:'labor',label:'Munkadíj',unit_price:12000,confirmed:true},{code:'maintenance_0',label:'Szállítás',unit:'m³',unit_price:1,confirmed:false}];
let items=math.build({data:{team_1_size:'4',team_1_arrival:'08:00',team_1_departure:'16:00'}},prices);
assert.equal(items[0].quantity,'1920');assert.equal(math.total(items),384000);
items=math.build({data:{team_1_size:'3',team_1_arrival:'08:09',team_1_departure:'08:20',team_2_size:'2',team_2_arrival:'09:00',team_2_departure:'09:07'}},prices);
assert.equal(math.total(items),9400);
assert.equal(math.total([{quantity:'1',unitPrice:'1234',divisor:60}]),20.57);
assert.equal(math.total([{quantity:'1',unitPrice:'1',divisor:60},{quantity:'1',unitPrice:'1',divisor:60}]),0.03,'Only round the total');
assert.equal(math.total([{quantity:'1,5',unitPrice:'12,50',divisor:1}]),18.75);
for(const input of ['-1','NaN','Infinity','1e3','',null])assert.throws(()=>math.total([{quantity:input,unitPrice:'1',divisor:1}]));
assert.throws(()=>math.total([{quantity:'1',unitPrice:'-2',divisor:1}]));
assert.throws(()=>math.total([{quantity:'1',unitPrice:'2',divisor:0}]));
items=math.build({data:{team_1_size:'2',team_1_arrival:'16:00',team_1_departure:'08:00',maintenance_0:'1,5'}},prices);
assert.equal(items[0].reviewed,false);assert.equal(items[0].quantity,'0');assert.equal(items[1].reviewed,false);
assert.equal(math.minutes('25:00'),null);assert.equal(math.minutes('08:60'),null);
items=math.build({data:{team_1_size:'4',team_1_arrival:'08:00',team_1_departure:'16:00'},billingMode:'flat_monthly'},prices);
assert.equal(math.total(items),384000,'Flat customers retain hourly valuation');
const earthPrices=[...prices,{code:'construction_3',label:'Föld elszállítása',unit:'m³',unit_price:123,confirmed:true},{code:'extra_earth_freight',label:'Fuvardíj',unit:'fuvar',unit_price:456,confirmed:true}];
items=math.build({data:{construction_3:'2,5'}},earthPrices);
assert.equal(items.length,2);assert.equal(math.total(items),763.5);assert.equal(items[1].reviewed,false,'Freight quantity needs office confirmation');
for(const value of ['', '0', '-1', 'hibás'])assert.equal(math.build({data:{construction_3:value}},earthPrices).filter(i=>i.label==='Fuvardíj').length,0);
assert.equal(math.build({data:{}},earthPrices).length,0,'Catalog extras are not automatically charged');
console.log('PASS: person-minutes, multiple teams, decimal units, rounding, invalid inputs, provisional prices, flat-rate valuation and separate earth freight.');
